name: Run BDD Cucumber Tests on Windows

on:
  workflow_dispatch: 
    inputs: 
      browser:
        type: choice
        required: true
        description: provide the browser
        default: Chrome
        options:
          - Chrome
          - Firefox
      username:
        required: true
        description: provide the login username
        default: Demo-user
      password:
        required: true
        description: provide the login password
        default: Demo-pwd

jobs:
  run-bdd-tests:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4.6.0
        with:
          java-version: "11" # Update to match your project needs
          distribution: "temurin"
          architecture: "x64"

      # Step 3: Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
          architecture: "x64"

      # Step 4: Run BDD Cucumber Tests
      - name: Run Cucumber Tests
        run: mvn clean test -Dbrowser={{github.event.inputs.browser}} -Dusername=${{github.event.inputs.username}} -Dpassword=${{github.event.inputs.password}}
        shell: cmd

      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/cucumber-report-html/cucumber-html-reports
